//! Setup/reconciliation execution for auth capabilities.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use ready_set_sdk::change_log::{ChangeLog, ChangeOp, ChangeRecord, backup_file};
use ready_set_sdk::fs::{atomic_write, sha256_bytes, sha256_file};
use ready_set_sdk::{
    CapabilityAction, CapabilityActionKind, CapabilityRunReport, CapabilityVerb, Context, Error,
    Output, OutputMode, Result, RunStatus,
};
use time::OffsetDateTime;

use crate::options::SetOptions;
use crate::readiness::{self, AuthAudit, AuthCheck, CheckLevel};
use crate::{CAPABILITY_ID, PROVIDER_ID, is_auth_capability};

const PLAN_PATH: &str = ".ready-set/plugins/auth/implementation-plan.md";

const IMPLEMENTATION_STEPS: &[&str] = &[
    "Choose the application boundary that owns login start, OAuth callback handling, and session creation.",
    "Configure OAuth/OIDC providers with client ids, client secrets where required, redirect URIs, and requested scopes.",
    "Add callback handling that validates state, exchanges the authorization code, and verifies the provider identity.",
    "Persist the provider identity in the app's account model so repeat logins resolve to the same local user.",
    "Bridge the verified provider identity to the app's existing session, token, or device-auth mechanism.",
    "Expose login entry points in the client or CLI and route them to the provider start flow.",
    "Document required provider environment variables in the project's example config files.",
    "Run `ready-set go auth` and the app's own auth tests before enabling the flow in production.",
];

struct PlannedWrite {
    abs: PathBuf,
    content: String,
    rel: String,
    op: ChangeOp,
    before_content: Option<String>,
}

/// Execute `set` for the auth capability.
///
/// # Errors
///
/// Forwards SDK errors from I/O, JSON output, or change-log writes.
pub fn set_capability(
    capability: &str,
    root: &Path,
    opts: &SetOptions,
    ctx: &Context,
) -> Result<CapabilityRunReport> {
    if !is_auth_capability(capability) {
        return Err(Error::contract(format!(
            "unknown capability `{capability}` for provider `{PROVIDER_ID}`"
        )));
    }

    let audit = readiness::audit_project(root);
    let mut actions = Vec::new();
    let mut planned_writes = Vec::new();
    plan_implementation_plan(root, &audit, opts, &mut actions, &mut planned_writes);
    execute_planned_writes(root, opts, &mut actions, &planned_writes)?;

    let status = if planned_writes.is_empty() || opts.dry_run {
        RunStatus::Noop
    } else {
        RunStatus::Changed
    };
    let report = CapabilityRunReport {
        id: CAPABILITY_ID.into(),
        verb: CapabilityVerb::Set,
        status,
        actions,
    };
    render_report(&report, opts, ctx)?;
    Ok(report)
}

fn plan_implementation_plan(
    root: &Path,
    audit: &AuthAudit,
    opts: &SetOptions,
    actions: &mut Vec<CapabilityAction>,
    planned_writes: &mut Vec<PlannedWrite>,
) {
    let abs = root.join(PLAN_PATH);
    let content = render_plan(audit);
    let current = std::fs::read_to_string(&abs).ok();
    match current {
        Some(current) if current == content => {
            actions.push(check(PLAN_PATH, "implementation plan already up to date"));
        },
        Some(current) if opts.force => {
            planned_writes.push(PlannedWrite {
                abs,
                content,
                rel: PLAN_PATH.into(),
                op: ChangeOp::Modify,
                before_content: Some(current),
            });
        },
        Some(_) => {
            actions.push(skip(
                PLAN_PATH,
                "implementation plan differs; pass --force to overwrite",
            ));
        },
        None => {
            planned_writes.push(PlannedWrite {
                abs,
                content,
                rel: PLAN_PATH.into(),
                op: ChangeOp::Create,
                before_content: None,
            });
        },
    }
}

fn render_plan(audit: &AuthAudit) -> String {
    let mut out = String::new();
    out.push_str("# Auth Integration Plan\n\n");
    out.push_str("Generated by `ready-set-auth`. Re-run `ready-set set auth --force` after auth code changes to refresh this plan.\n\n");
    if audit.recognized_project {
        out.push_str("The audit found an existing web-auth surface. Treat the paths below as hints, not as required architecture.\n\n");
    } else {
        out.push_str("No existing web-auth surface was detected. Use this as a provider-neutral OAuth/OIDC integration template for your app architecture.\n\n");
    }

    push_current_audit(&mut out, audit);
    push_open_items(&mut out, audit);
    push_implementation_steps(&mut out);
    push_useful_commands(&mut out);
    out
}

fn push_current_audit(out: &mut String, audit: &AuthAudit) {
    out.push_str("## Current Audit\n\n");
    if !audit.recognized_project {
        out.push_str("- No app-specific auth layout was recognized, so no path-level audit hints are included.\n");
        return;
    }

    for check in &audit.checks {
        let marker = if check.passed { "x" } else { " " };
        let level = level_label(check.level);
        let status = if check.passed { "complete" } else { "open" };
        let path = check.path.as_deref().unwrap_or("-");
        writeln!(
            out,
            "- [{marker}] `{}` ({level}, {status}; hint: `{path}`)",
            plan_check_title(check),
        )
        .expect("writing to a string cannot fail");
    }
}

fn push_open_items(out: &mut String, audit: &AuthAudit) {
    out.push_str("\n## Open Items\n\n");
    if !audit.recognized_project {
        out.push_str("- Apply the generic implementation order below to the framework, routing layer, storage layer, and account model used by this project.\n");
        return;
    }

    let failures = audit.required_failures();
    if failures.is_empty() {
        out.push_str("- Required auth checks are complete. Keep this plan as a record of the integration shape.\n");
        return;
    }

    for check in failures {
        let path = check
            .path
            .as_deref()
            .unwrap_or("the relevant application files");
        writeln!(
            out,
            "- `{}`: map this check onto `{path}` or the equivalent boundary in your architecture.",
            plan_check_title(check),
        )
        .expect("writing to a string cannot fail");
    }
}

fn push_implementation_steps(out: &mut String) {
    out.push_str("\n## Implementation Order\n\n");
    for (index, step) in IMPLEMENTATION_STEPS.iter().enumerate() {
        writeln!(out, "{}. {step}", index + 1).expect("writing to a string cannot fail");
    }
}

fn push_useful_commands(out: &mut String) {
    out.push_str("\n## Useful Commands\n\n");
    out.push_str("- `ready-set ready auth`\n");
    out.push_str("- `ready-set go --json auth`\n");
    out.push_str("- `ready-set-auth __ready auth`\n");
}

const fn level_label(level: CheckLevel) -> &'static str {
    match level {
        CheckLevel::Required => "required",
        CheckLevel::Advisory => "advisory",
    }
}

fn plan_check_title(check: &AuthCheck) -> &'static str {
    match check.id {
        "oauth-routes" => "OAuth start and callback routes",
        "session-bridge" => "session or account bridge",
        "provider-identity-storage" => "provider identity storage",
        "oauth-provider-config" => "OAuth provider configuration",
        "login-entry-points" => "login entry points",
        "local-ready-set-auth-source" => "local auth package source",
        "invite-only-signup" => "account creation policy",
        _ => check.title,
    }
}

fn execute_planned_writes(
    root: &Path,
    opts: &SetOptions,
    actions: &mut Vec<CapabilityAction>,
    planned_writes: &[PlannedWrite],
) -> Result<()> {
    let mut log = if opts.dry_run || planned_writes.is_empty() {
        None
    } else {
        Some(ChangeLog::open(root, PROVIDER_ID)?)
    };

    for write in planned_writes {
        if opts.dry_run {
            actions.push(skip(&write.rel, "plan only"));
            continue;
        }

        let before_sha = write
            .before_content
            .as_ref()
            .map(|previous| sha256_bytes(previous.as_bytes()));
        if matches!(write.op, ChangeOp::Modify) && write.abs.is_file() {
            backup_file(root, &write.abs)?;
        }
        atomic_write(&write.abs, write.content.as_bytes())?;
        let after_sha = sha256_file(&write.abs)?;
        if let Some(log) = log.as_mut() {
            log.record(&ChangeRecord {
                op: write.op,
                path: relative_path(root, &write.abs),
                before_sha256: before_sha,
                after_sha256: Some(after_sha),
                ts: OffsetDateTime::now_utc(),
            })?;
        }
        actions.push(CapabilityAction {
            kind: match write.op {
                ChangeOp::Create => CapabilityActionKind::Create,
                ChangeOp::Modify => CapabilityActionKind::Modify,
                ChangeOp::Delete => CapabilityActionKind::Delete,
            },
            summary: "written".into(),
            path: Some(write.rel.clone()),
        });
    }

    Ok(())
}

fn render_report(report: &CapabilityRunReport, opts: &SetOptions, ctx: &Context) -> Result<()> {
    let mut out = Output::for_context(ctx, std::io::stdout());
    if matches!(ctx.output_mode(), OutputMode::Json) {
        out.json(report)?;
        return Ok(());
    }

    if opts.dry_run {
        out.human("ready-set-auth set auth (dry-run)");
    } else {
        out.human("ready-set-auth set auth");
    }
    for action in &report.actions {
        let path = action.path.as_deref().unwrap_or("-");
        out.human(&format!(
            "  {:<8} {:<56} {}",
            action_kind_label(action.kind),
            path,
            action.summary
        ));
    }
    Ok(())
}

fn check(path: impl Into<String>, summary: impl Into<String>) -> CapabilityAction {
    CapabilityAction {
        kind: CapabilityActionKind::Check,
        summary: summary.into(),
        path: Some(path.into()),
    }
}

fn skip(path: impl Into<String>, summary: impl Into<String>) -> CapabilityAction {
    CapabilityAction {
        kind: CapabilityActionKind::Skip,
        summary: summary.into(),
        path: Some(path.into()),
    }
}

const fn action_kind_label(kind: CapabilityActionKind) -> &'static str {
    match kind {
        CapabilityActionKind::Create => "create",
        CapabilityActionKind::Modify => "modify",
        CapabilityActionKind::Delete => "delete",
        CapabilityActionKind::Run => "run",
        CapabilityActionKind::Check => "check",
        CapabilityActionKind::Skip => "skip",
        CapabilityActionKind::Error => "error",
    }
}

fn relative_path(root: &Path, abs: &Path) -> PathBuf {
    abs.strip_prefix(root).map_or_else(
        |_| abs.to_path_buf(),
        |path| PathBuf::from(path.to_string_lossy().replace('\\', "/")),
    )
}
