//! Renderers for the files `secrets set` writes.

use std::collections::BTreeSet;

use crate::{GITIGNORE_BEGIN, GITIGNORE_END};

const GITIGNORE_BODY: &str =
    ".env\n.env.*\n!.env.example\n/secrets/\n.ready-set/plugins/secrets/rotations.jsonl\n";

const GITLEAKS_TEMPLATE: &str = include_str!("templates/gitleaks.toml");

/// Render the desired `.env.example` content given the detected names plus the
/// user-curated prelude that already lived in the file.
///
/// `prelude` is the part of an existing `.env.example` that lived outside the
/// managed block (preserves comments, ordering). `user_keys` is the set of keys
/// already declared in the prelude — these are kept as-is and excluded from the
/// managed block so we don't duplicate them.
#[must_use]
pub fn render_env_example(
    prelude: &str,
    user_keys: &BTreeSet<String>,
    all_detected: &BTreeSet<String>,
) -> String {
    let managed_keys: Vec<&String> = all_detected
        .iter()
        .filter(|name| !user_keys.contains(*name))
        .collect();

    let mut out = String::new();
    let prelude_trimmed = prelude.trim_end_matches('\n');
    if !prelude_trimmed.is_empty() {
        out.push_str(prelude_trimmed);
        out.push('\n');
        out.push('\n');
    }
    out.push_str(GITIGNORE_BEGIN);
    out.push('\n');
    out.push_str("# Auto-detected by `ready-set set secrets`. Edit values or move keys out\n");
    out.push_str("# of this block to pin them. Re-run `ready-set set secrets` after changes.\n");
    if managed_keys.is_empty() {
        out.push_str("# (no auto-detected keys)\n");
    } else {
        for key in managed_keys {
            out.push_str(key);
            out.push_str("=\n");
        }
    }
    out.push_str(GITIGNORE_END);
    out.push('\n');
    out
}

/// Render a canonical fake-value dotenv template from detected secret names.
///
/// The generated file is intentionally safe to commit. It is not a secret
/// store; users copy or encrypt it, then replace placeholders in their secure
/// location.
#[must_use]
pub fn render_canonical_env_template(all_detected: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("# Generated by ready-set set secrets.\n");
    out.push_str("# Fake values only. Put real values in ReadySet bundles, password managers, cloud provider dashboards, or provider CLIs.\n");
    out.push_str("# Do not paste real secrets into this template.\n\n");
    if all_detected.is_empty() {
        out.push_str("# No env vars detected.\n");
        return out;
    }
    for key in all_detected {
        out.push_str(key);
        out.push('=');
        out.push_str(fake_value_for_key(key));
        out.push('\n');
    }
    out
}

// A one-row-per-key fake-value table: distinct keys that happen to share a
// value (e.g. several booleans) are kept as separate arms for readability.
#[allow(clippy::match_same_arms)]
fn fake_value_for_key(key: &str) -> &'static str {
    match key {
        "APP_ENV" => "development",
        "APP_ORIGIN" => "http://localhost:3000",
        "API_ORIGIN" => "http://127.0.0.1:8787",
        "BIND_ADDR" => "127.0.0.1:8787",
        "COOKIE_SECURE" => "false",
        "DATABASE_URL" | "NEON_DATABASE_URL" | "NEON_DB" => {
            "postgres://user:password@localhost:5432/appdb"
        },
        "ENABLE_HSTS" => "0",
        "LIBSQL_URL" => "libsql://database-org.turso.io",
        "MAIL_APP_NAME" | "SMTP_FROM_NAME" => "Example App",
        "MEDIA_STORAGE" => "auto",
        "PRIVATE_MEDIA_DIR" => "data/media",
        "MEDIA_MAX_BYTES" => "8388608",
        "PASSWORD_RESET_EMAIL_SUBJECT" => "Reset your Example App password",
        "SMTP_PORT" => "587",
        "SMTP_TLS" => "starttls",
        "SMTP_HOST" => "smtp.example.invalid",
        "PASSWORD_RESET_ENABLED" => "true",
        "PASSWORD_RESET_DEBUG" => "false",
        "PASSWORD_RESET_TOKEN_TTL_SECONDS" => "1800",
        "SESSION_TTL_SECONDS" => "43200",
        "REMEMBER_SESSION_TTL_SECONDS" => "2592000",
        "R2_BUCKET" => "example-private-media",
        "R2_ENDPOINT" => "https://account-id.r2.cloudflarestorage.com",
        "R2_REGION" => "auto",
        "R2_BACKUP_PREFIX" => "backups/db",
        "R2_BACKUP_MAX_AGE_HOURS" => "30",
        "R2_BACKUP_KEEP_RECENT" => "7",
        "R2_BACKUP_KEEP_DAILY" => "7",
        "R2_BACKUP_KEEP_WEEKLY" => "4",
        "R2_BACKUP_KEEP_MONTHLY" => "3",
        "MONITOR_CHECK_DEEP" | "MONITOR_CHECK_BACKUPS" => "0",
        "LAMBDA_BASE_URL" => "https://api.lambda.ai/v1",
        "LAMBDA_MODEL" => "llama3.1-70b-instruct-fp8",
        "AUTHORIZED_USERS" | "ADMIN_USERS" => "user@example.invalid=$argon2id$fake-hash",
        "ACCOUNT_ID" | "R2_ACCOUNT_ID" | "CLOUDFLARE_ACCOUNT_ID" | "SLACK_APP_ID" => {
            "replace-with-provider-id"
        },
        "SECRET_ACCESS_KEY_ID" => "replace-with-secure-value",
        "ACCESS_KEY_ID" | "R2_ACCESS_KEY_ID" | "S3_ACCESS_KEY_ID" => "replace-with-access-key-id",
        _ if key.contains("EMAIL") || key == "SMTP_FROM" => "user@example.invalid",
        _ if key.ends_with("_URL") || key.ends_with("_ORIGIN") || key.ends_with("_ENDPOINT") => {
            "https://example.invalid"
        },
        _ if key.ends_with("_KEY_ID") => "replace-with-access-key-id",
        _ if key.ends_with("_TOKEN")
            || key.ends_with("_SECRET")
            || key.ends_with("_KEY")
            || key.ends_with("_PASSWORD")
            || key.ends_with("_PASSPHRASE") =>
        {
            "replace-with-secure-value"
        },
        _ => "",
    }
}

/// Plan the `.gitignore` content for a project root.
///
/// Mirrors the merge strategy in `ready-set-rust/src/gitignore.rs`: only the
/// content between this plugin's namespaced markers is touched, leaving any
/// other managed block (including `ready-set-rust`'s) untouched.
#[must_use]
pub fn plan_gitignore(current: Option<&str>) -> Option<String> {
    let desired = render_gitignore_block();
    match current {
        None => Some(desired),
        Some(text) => {
            let merged = merge_managed(text, &desired);
            if merged == text { None } else { Some(merged) }
        },
    }
}

fn render_gitignore_block() -> String {
    let mut out = String::new();
    out.push_str(GITIGNORE_BEGIN);
    out.push('\n');
    out.push_str(GITIGNORE_BODY.trim_end());
    out.push('\n');
    out.push_str(GITIGNORE_END);
    out.push('\n');
    out
}

fn merge_managed(existing: &str, managed_block: &str) -> String {
    let begin = format!("{GITIGNORE_BEGIN}\n");
    let end = format!("{GITIGNORE_END}\n");

    if let (Some(b), Some(e)) = (existing.find(&begin), existing.find(&end))
        && b < e
    {
        let mut out = String::with_capacity(existing.len() + managed_block.len());
        out.push_str(&existing[..b]);
        out.push_str(managed_block);
        let after = e + end.len();
        if after < existing.len() {
            out.push_str(&existing[after..]);
        }
        return out;
    }

    let mut out = String::with_capacity(existing.len() + managed_block.len() + 1);
    out.push_str(existing);
    if !existing.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(managed_block);
    out
}

/// Strip this plugin's managed block from `existing`, returning the remaining
/// content.
#[must_use]
pub fn strip_managed_block(existing: &str) -> String {
    let begin = format!("{GITIGNORE_BEGIN}\n");
    let end = format!("{GITIGNORE_END}\n");
    if let (Some(b), Some(e)) = (existing.find(&begin), existing.find(&end))
        && b < e
    {
        let mut out = String::with_capacity(existing.len());
        out.push_str(&existing[..b]);
        let after = e + end.len();
        if after < existing.len() {
            out.push_str(&existing[after..]);
        }
        return out;
    }
    existing.to_owned()
}

/// The default `.gitleaks.toml` template.
#[must_use]
pub const fn gitleaks_template() -> &'static str {
    GITLEAKS_TEMPLATE
}

#[cfg(test)]
mod tests {
    use super::*;

    fn keys(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(|s| (*s).to_string()).collect()
    }

    #[test]
    fn env_example_groups_user_pinned_first() {
        let prelude = "# Comments\nPINNED=value\n";
        let user = keys(&["PINNED"]);
        let detected = keys(&["PINNED", "DETECTED_A", "DETECTED_B"]);
        let rendered = render_env_example(prelude, &user, &detected);
        assert!(rendered.contains("PINNED=value"));
        assert!(rendered.contains("DETECTED_A="));
        assert!(rendered.contains("DETECTED_B="));
        // The user-pinned key is not duplicated in the managed block.
        assert_eq!(rendered.matches("PINNED").count(), 1);
    }

    #[test]
    fn env_example_managed_block_alone_when_no_prelude() {
        let user = BTreeSet::new();
        let detected = keys(&["A", "B"]);
        let rendered = render_env_example("", &user, &detected);
        assert!(rendered.starts_with("# >>> ready-set-encrypt"));
        assert!(rendered.contains("A=\nB=\n"));
    }

    #[test]
    fn canonical_template_uses_safe_fake_values() {
        let rendered = render_canonical_env_template(&keys(&[
            "DATABASE_URL",
            "R2_ENDPOINT",
            "SECRET_ACCESS_KEY_ID",
            "SESSION_SECRET",
        ]));

        assert!(rendered.contains("DATABASE_URL=postgres://user:password@localhost:5432/appdb"));
        assert!(rendered.contains("R2_ENDPOINT=https://account-id.r2.cloudflarestorage.com"));
        assert!(rendered.contains("SECRET_ACCESS_KEY_ID=replace-with-secure-value"));
        assert!(rendered.contains("SESSION_SECRET=replace-with-secure-value"));
        assert!(rendered.contains("Do not paste real secrets"));
    }

    #[test]
    fn gitignore_plan_creates_when_missing() {
        let plan = plan_gitignore(None).unwrap();
        assert!(plan.contains("# >>> ready-set-encrypt managed >>>"));
        assert!(plan.contains(".env\n"));
        assert!(plan.contains("secrets/\n"));
    }

    #[test]
    fn gitignore_plan_is_noop_when_already_present() {
        let initial = plan_gitignore(None).unwrap();
        assert!(plan_gitignore(Some(&initial)).is_none());
    }

    #[test]
    fn gitignore_preserves_other_managed_blocks() {
        let rust_block = "# >>> ready-set managed >>>\ntarget/\n# <<< ready-set managed <<<\n";
        let merged = plan_gitignore(Some(rust_block)).unwrap();
        assert!(merged.contains("# >>> ready-set managed >>>"));
        assert!(merged.contains("# >>> ready-set-encrypt managed >>>"));
        assert!(merged.contains("target/\n"));
        assert!(merged.contains(".env\n"));
    }

    #[test]
    fn gitignore_replaces_only_own_block_on_drift() {
        let mixed = "user-line\n# >>> ready-set-encrypt managed >>>\nold-content\n# <<< ready-set-encrypt managed <<<\nmore-user\n";
        let merged = plan_gitignore(Some(mixed)).unwrap();
        assert!(merged.starts_with("user-line\n"));
        assert!(merged.contains("more-user\n"));
        assert!(merged.contains(".env\n"));
        assert!(!merged.contains("old-content"));
    }

    #[test]
    fn strip_managed_block_returns_input_when_absent() {
        let input = "no-markers-here\n";
        assert_eq!(strip_managed_block(input), input);
    }
}
