[package]
name         = "ready-set-rust"
version      = "0.1.0"
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
description   = "Rust capability provider plugin for ready-set."
documentation = "https://docs.rs/ready-set-rust"
homepage      = "https://github.com/pulsearc-ai/ReadySet"
readme        = "README.md"
keywords      = ["ready-set", "rust", "plugin"]
categories    = ["command-line-utilities", "development-tools"]

[[bin]]
name = "ready-set-rust"
path = "src/main.rs"

[dependencies]
ready-set-sdk = { workspace = true }
clap          = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
semver        = { workspace = true }
time          = { workspace = true }
toml          = { workspace = true }
toml_edit     = { workspace = true }
walkdir       = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
